# Default values for mackerel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: mackerel/mackerel-agent
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

mackerel:
  apikey: INSERTYOURAPIKEYHERE
  service: YOURSERVICE
  role: YOURROLE
  enable_docker_plugin: 1
