apiVersion: kirishikistudios.com/v1alpha1
kind: Mackerel
metadata:
  name: example-mackerel
spec:
  # Default values copied from <project_dir>/helm-charts/mackerel/values.yaml
  
  # Default values for mackerel.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  
  image:
    repository: mackerel/mackerel-agent
    tag: latest
    pullPolicy: IfNotPresent
  
  nameOverride: ""
  fullnameOverride: ""
  
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  mackerel:
    apikey: xxxxx
    service: minikube
    role: mbp13

